### ISSUE TITLE
 [question] is this check for udp traffic suitable, too?

### ISSUE THREAD

**Issue by tlo8640** [matteocorti/check_tcptraffic#6]
Hello,
this is more a question, than a bug.
I know, the description means ..plugin for checking tcp traffic...
but since it uses /proc/net/dev is the udp traffic also included in traffic counting?
If no, is there a plugin for monitong udp traffic, too?
Thank you
Thomas

**Comment by matteocorti** [comment]
You are right, the naming of the plugin was an error. It's a check on the interface.

**Comment by matteocorti** [comment]
Fixed in 3.0.0
